server:
  port: 8082


spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/realty-management
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
    jwt:
      secret: ${JWT_SECRET}
  mail:
    username: ${MAIL_USERNAME}
    port: 587
    host: smtp.gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.security: DEBUG

