server:
  port: 8082


spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  datasource:
    url: DB_URL
    username: DB_USERNAME
    password: DB_PASSWORD
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: SECURITY_USERNAME
      password: SECURITY_PASSWORD
  mail:
    username: MAIL_USERNAME
    port: 587
    host: smtp.gmail.com
    password: MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG

