server:
  port: 8082


spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/realty-management
    username: realty
    password: realty
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: 123456
    jwt:
      secret: "salihsalihsalisahlikdsalihsalihsalihsailhsalihsalihsalihsalihsalihsalih"
  mail:
    username: asbahattinsalih7@gmail.com
    port: 587
    host: smtp.gmail.com
    password: xlqthlihygmwijzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG

