server:
  port: 8082
  servlet:
    context-path: /api/realty-management


spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/realty-management
    username: realty
    password: realty
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  security:
    user:
      name: admin
      password: 123456
    jwt:
      secret: "salihsalihsalisahlikdsalihsalihsalihsailhsalihsalihsalihsalihsalihsalih"

  mail:
    username: asbahattinsalih7@gmail.com
    port: 587
    host: smtp.gmail.com
    password: xlqthlihygmwijzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.security: DEBUG

