name: RealtyHub CI/CD Pipeline

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main", "develop", "feature/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run Tests
        run: mvn test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
          --build-arg DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
          --build-arg SECURITY_USER_NAME=${{ secrets.SECURITY_USER_NAME }} \
          --build-arg SECURITY_USER_PASSWORD=${{ secrets.SECURITY_USER_PASSWORD }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
          --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
          --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB}} \
          --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -t ${{ secrets.DOCKER_USERNAME }}/realtyhub:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/realtyhub:latest