name: Deploy Application

on:
  push:
    branches:
      - main  # Bu branch'a yapılan push işlemiyle tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Kodu checkout et
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Java kurulumu
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # İstediğin Java versiyonunu buraya yazabilirsin

      # 3. Secrets ile çevresel değişkenleri ayarla
      - name: Set environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "SECURITY_USER_NAME=${{ secrets.SECURITY_USER_NAME }}" >> $GITHUB_ENV
          echo "SECURITY_USER_PASSWORD=${{ secrets.SECURITY_USER_PASSWORD }}" >> $GITHUB_ENV

      # 4. Spring Boot uygulamasını build et ve deploy et
      - name: Build and deploy
        run: |
          ./mvnw clean install  # Maven ile build
          java -jar target/your-application.jar  # Eğer .jar dosyası kullanıyorsan
